# Generated by Django 3.1.1 on 2020-11-20 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descreption',
            new_name='description',
        ),
    ]
